Upgrade drone

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -3,6 +3,16 @@ pipeline:
     image: plugins/git
     depth: 1
 
+  check:
+    image: docker
+    commands:
+      - |
+        cat << ListEOF
+        58c2644c928cc4772e45973e2e3d0da8  .drone.env
+        ea74a6e24f1baaa4ea0afd2bcf7f6820  docker/docker-entrypoint.sh
+        cdda80cb2966b96965357b9c576bd492  docker/Dockerfile
+        ListEOF | md5sum -wc -
+
   build:
     image: docker
     volumes:
@@ -12,7 +22,7 @@ pipeline:
       - >-
         docker build -t "$IMAGE_BUILD"
         --label branch="$DRONE_COMMIT_BRANCH"
-        . | awk '!/\r/'
+        --build-arg GITHUB_AUTH_TOKEN="$GITHUB_AUTH_TOKEN" .
 
   test:
     image: docker
@@ -26,24 +36,38 @@ pipeline:
         -e SYMFONY_DEBUG=0
         "$IMAGE_BUILD"
 
-  publish:
-    image: docker
-    volumes:
-      - /var/run/docker.sock:/var/run/docker.sock
-    commands:
-      - source .drone.env
-      - docker login -u"$HUB_LOGIN" -p"$HUB_PASSWORD" registry.gitlab.com
-      - docker tag "$IMAGE_BUILD" "$IMAGE_PUSH"
-      - docker push "$IMAGE_PUSH" > /dev/null
-      - >+
-        if [ "master" == "$DRONE_COMMIT_BRANCH" ]; then
-          docker rmi --force "$IMAGE_PUSH"
+#  publish:
+#    image: docker
+#    volumes:
+#      - /var/run/docker.sock:/var/run/docker.sock
+#    commands:
+#      - source .drone.env
+#      - docker login -u"$HUB_LOGIN" -p"$HUB_PASSWORD" registry.gitlab.com
+#      - docker tag "$IMAGE_BUILD" "$IMAGE_PUSH"
+#      - docker push "$IMAGE_PUSH" > /dev/null
+#      - >+
+#        if [ "master" == "$DRONE_COMMIT_BRANCH" ]; then
+#          docker rmi --force "$IMAGE_PUSH"
+#
+#          docker tag "$IMAGE_BUILD" "$IMAGE_LATEST"
+#          docker push "$IMAGE_LATEST" > /dev/null
+#        fi
+#    when:
+#      event: push
 
-          docker tag "$IMAGE_BUILD" "$IMAGE_LATEST"
-          docker push "$IMAGE_LATEST" > /dev/null
-        fi
-    when:
-      event: push
+#  clean:
+#    image: docker
+#    volumes:
+#      - /var/run/docker.sock:/var/run/docker.sock
+#    commands:
+#      - source .drone.env
+#      - >+
+#        if [ "success" == "$DRONE_BUILD_STATUS" ] && [ "push" == "$DRONE_BUILD_EVENT" ]; then
+#          (docker rmi `docker images -q --filter before="$IMAGE_BUILD" --filter label="branch=$DRONE_COMMIT_BRANCH" "$IMAGE"`)
+#        fi
+#      - docker rmi --force "$IMAGE_BUILD"
+#    when:
+#      status: [ failure, success ]
 
   clean:
     image: docker
@@ -51,22 +75,28 @@ pipeline:
       - /var/run/docker.sock:/var/run/docker.sock
     commands:
       - source .drone.env
-      - >+
-        if [ "success" == "$DRONE_BUILD_STATUS" ] && [ "push" == "$DRONE_BUILD_EVENT" ]; then
-          (docker rmi `docker images -q --filter before="$IMAGE_BUILD" --filter label="branch=$DRONE_COMMIT_BRANCH" "$IMAGE"`)
-        fi
       - docker rmi --force "$IMAGE_BUILD"
     when:
-      status: [ failure, success ]
+      status: failure
+
+#  deploy:
+#    image: plugins/ssh
+#    host:
+#      - s2.automagistre.ru
+#    user: premier
+#    port: 22
+#    script:
+#      - source .drone.env
+#      - docker service update --image "$IMAGE_PUSH" astra50_app
+#      - docker rmi `docker images -q --filter "before=$IMAGE_PUSH" "$IMAGE"` 2> /dev/null || true
+#    when:
+#      branch: master
 
   deploy:
-    image: plugins/ssh
-    host:
-      - s2.automagistre.ru
-      - s1.grachevko.ru
-    user: premier
-    port: 22
-    script:
+    image: docker
+    volumes:
+      - /var/run/docker.sock:/var/run/docker.sock
+    commands:
       - source .drone.env
       - docker service update --image "$IMAGE_PUSH" astra50_app
       - docker rmi `docker images -q --filter "before=$IMAGE_PUSH" "$IMAGE"` 2> /dev/null || true
